user: ctsdb # 数据库账号
password: ctsdbj # 数据库密码
dsn: 173.168.5.241/ctsdb


#user: ctsdb # 数据库账号
#password: ctsdb # 数据库密码
#dsn: 172.22.16.32/ctsdb



sql:
  tradedate: select tradedate from sysconfig # 获取交易日期sql
  version: SELECT VERSION FROM VERSIONCONTROL WHERE TYPEID ='globalConst' # 获取cts版本
  laststartupdate: select laststartupdate from sysconfig